apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-apps
      targetRevision: 2.0.4
      helm:
        releaseName: local-k8s-apps
        valueFiles:
          - $repo/apps.yaml
    - repoURL: https://github.com/sivanesh-dsp/local-argocd-apps.git
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
